### ISSUE TITLE
Next and previous

### ISSUE THREAD

**Issue by cyber12drago** [2018-PemrogramanWeb-B/tugas7-fp-lipsa#1]
Kegunaan next dan previous hanya menampilkan foto/tulisan yang sama

![1545195627693](https://user-images.githubusercontent.com/36811855/50199849-bc86df00-0385-11e9-9adf-ef0e40b4c078.jpg)

**Comment by heirsall** [comment]
Sebelumnya karena gambar belum diambil untuk disimpan di include php nya.
Fix: Gambar sudah ditambahkan dengan carousell untuk membuat slideshow.
