### ISSUE TITLE
Logo

### ISSUE THREAD

**Issue by rigold** [2018-PemrogramanWeb-B/tugas7-fp-lipsa#2]
![capture](https://user-images.githubusercontent.com/17819067/50201034-18079b80-038b-11e9-8114-8f419753c69d.PNG)
tidak semua logo ditampilkan dengan baik

**Comment by ilhamindiano** [comment]
karena layout masih belum dengan css dan logo masih belum diupload

fix:
css dan logo sudah dimasukkan
