### ISSUE TITLE
link

### ISSUE THREAD

**Issue by cluster777** [2018-PemrogramanWeb-B/tugas7-fp-lipsa#3]
![image](https://user-images.githubusercontent.com/42055002/50207413-003b1200-03a1-11e9-93b6-7e4bdb580f35.png)
link di dalam semua page mengarah ke dalam router di page itu sendiri
tidak mengarah sesuai link

**Comment by Bruvvv** [comment]
Link sudah diperbaiki, kesalahan terletak pada kurangnya penulisan "http://" dalam setiap link
