### ISSUE TITLE
Error ketika submit 

### ISSUE THREAD

**Issue by gslayer0** [2018-PemrogramanWeb-B/tugas7-fp-lipsa#4]
![image](https://user-images.githubusercontent.com/37019764/50229238-6ee99100-03dc-11e9-9d17-b6dc00d73cab.png)

**Comment by Bruvvv** [comment]
Error tersebut disebabkan jika user belum mengisi semua jawaban lalu mengklik tombol submit. 
Fix : Tombol Submit di disable hingga user sudah menginput semua jawaban agar mendapat hasil yang maksimal
