### ISSUE TITLE
Tidak responsive

### ISSUE THREAD

**Issue by mochimoe** [2018-PemrogramanWeb-B/tugas7-fp-lipsa#5]
ketika windows di perkecil, layoutnya jadi berantakan. background tidak mengcover seluruh windows.

[](url)
![screenshot 69](https://user-images.githubusercontent.com/35224493/50256547-55bb0180-0429-11e9-8d8e-7361c35917d2.png)

**Comment by mochimoe** [comment]
solusi : background-position: center;
          background-size: cover;
          background-repeat: no-repeat;
          background-attachment: fixed;

**Comment by Bruvvv** [comment]
Saat itu hostingan web memang beberapa kali bermasalah. Tetapi jika dibuka melalui localhost berjalan normal dan responsiv
