### ISSUE TITLE
Gambar

### ISSUE THREAD

**Issue by mochimoe** [2018-PemrogramanWeb-B/tugas7-fp-lipsa#6]
gambarnya terzoom in, baru nampak jelas jika layar windows dikecilkan

![screenshot 70](https://user-images.githubusercontent.com/35224493/50256669-ee518180-0429-11e9-8eac-b232813ec7b0.png)

**Comment by Bruvvv** [comment]
Jika melalui web hosting, gambar dalam page tersebut nampak terlihat lebih besar. Apabila dibuka melalui local host, gambar terlihat normal
